# Custom Language File for Launcher Customizer

[ejs.app]
title = "MRS Launcher"

[ejs.landing]
mediaLinkURL = "https://mysticred.space"
mediaGitHubURL = "https://github.com/peunsu/MRSLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/Z8j6ahF4MJ"

[ejs.settings]
sourceGithubLink = "https://github.com/peunsu/MRSLauncher"
supportLink = "https://github.com/peunsu/MRSLauncher/issues"

[ejs.welcome]
welcomeHeader = "Pixelhill"
welcomeDescription = "이거 만드는데 존나 힘들었습니다"
welcomeDescCTA = "여러분들은 이런거 하지말고 Chill한 사람이 되세요."
